import { useEffect, useRef, useState, type CSSProperties } from 'react';
import AngleFront from '../../../../assets/Landing/Landing__Showcase__angle-front.jpg';
import AngleThreeQuarter from '../../../../assets/Landing/Landing__Showcase__angle-threequarter.jpg';
import './Statement.css';

const PROBLEMS: string[] = [
  'Every listing needs a title, a description, and pricing typed in by hand',
  'Product photos need to be prepped before they can go live',
  'Customers ask the same questions in different chats, over and over',
  'Promoting a product means repeating the same work on every platform',
  'Orders and order details live across texts, notes, and spreadsheets',
];

function withDelay(seconds: number): CSSProperties {
  return { '--delay': `${seconds}s` } as CSSProperties;
}

/**
 * eloqwnt's "who we are" analog, reframed as "what is MerchForge": the
 * reality merchants live with, then the one thing that changes it — a
 * photo goes in, a polished, ready-to-publish product comes out. The
 * transformation visual uses the same real photo/generated-angle pair as
 * the rest of the page rather than an invented before/after.
 */
export default function Statement() {
  const sectionRef = useRef<HTMLElement>(null);
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const node = sectionRef.current;
    if (!node) return;

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setVisible(true);
          observer.disconnect();
        }
      },
      { threshold: 0.2 },
    );

    observer.observe(node);
    return () => observer.disconnect();
  }, []);

  return (
    <section
      ref={sectionRef}
      className={`statement mf-section${visible ? ' statement--visible' : ''}`}
      aria-label="What MerchForge does"
    >
      <div className="statement__inner mf-section__inner">
        <p className="mf-eyebrow">What is MerchForge</p>
        <h2 className="statement__headline mf-headline">
          Running a store shouldn't mean doing everything manually.
        </h2>

        <ul className="statement__list">
          {PROBLEMS.map((problem, i) => (
            <li key={problem} className="statement__item" style={withDelay(i * 0.06)}>
              <span className="statement__item-mark" aria-hidden="true" />
              <span className="statement__item-text">{problem}</span>
            </li>
          ))}
        </ul>

        <p className="statement__transition" style={withDelay(PROBLEMS.length * 0.06 + 0.1)}>
          Give MerchForge a photo and a few words, and it does the rest — a polished,
          ready-to-publish product, not just a saved draft.
        </p>

        <div
          className="statement__transform"
          style={withDelay(PROBLEMS.length * 0.06 + 0.25)}
          role="img"
          aria-label="A plain product photo on the left, transformed by MerchForge AI into a polished product photo on the right"
        >
          <figure className="statement__transform-shot statement__transform-shot--before">
            <img src={AngleFront} alt="The photo as uploaded, unedited" />
            <figcaption>What you upload</figcaption>
          </figure>

          <div className="statement__transform-arrow" aria-hidden="true">
            <span className="statement__transform-label">MerchForge AI</span>
          </div>

          <figure className="statement__transform-shot statement__transform-shot--after">
            <img src={AngleThreeQuarter} alt="The same product, generated by MerchForge in a polished new angle" />
            <figcaption>What MerchForge generates</figcaption>
          </figure>
        </div>
      </div>
    </section>
  );
}
