import { useEffect, useRef, useState, type CSSProperties } from 'react';
import useParallax from '../../hooks/useParallax';
import AngleFront from '../../../../assets/Landing/Landing__Showcase__angle-front.jpg';
import AngleBack from '../../../../assets/Landing/Landing__Showcase__angle-back.jpg';
import AngleLeft from '../../../../assets/Landing/Landing__Showcase__angle-left.jpg';
import AngleThreeQuarter from '../../../../assets/Landing/Landing__Showcase__angle-threequarter.jpg';
import ColorA from '../../../../assets/Landing/Landing__Showcase__color-a.jpg';
import './ProductShowcase.css';

function withDelay(seconds: number): CSSProperties {
  return { '--delay': `${seconds}s` } as CSSProperties;
}

/**
 * The visual centerpiece of the page: a large-format editorial gallery of
 * real MerchForge output — the original uploaded photo plus the real
 * angle and color variants MerchForge generated from it. No mockups, no
 * stock photography.
 */
export default function ProductShowcase() {
  const sectionRef = useRef<HTMLElement>(null);
  const [visible, setVisible] = useState(false);
  const heroParallax = useParallax<HTMLDivElement>(0.06);
  const tileParallax = useParallax<HTMLDivElement>(-0.05);

  useEffect(() => {
    const node = sectionRef.current;
    if (!node) return;

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setVisible(true);
          observer.disconnect();
        }
      },
      { threshold: 0.1 },
    );

    observer.observe(node);
    return () => observer.disconnect();
  }, []);

  return (
    <section
      ref={sectionRef}
      className={`product-showcase mf-section${visible ? ' product-showcase--visible' : ''}`}
      aria-label="Real MerchForge-generated product imagery"
      id="showcase"
    >
      <div className="product-showcase__inner mf-section__inner">
        <p className="mf-eyebrow">Generated imagery</p>
        <h2 className="product-showcase__headline mf-headline">
          One photo in. A full product shoot out.
        </h2>
        <p className="mf-subtext product-showcase__subtext">
          Every image below started as the single photo on the left — MerchForge generated
          the rest, automatically.
        </p>

        <div
          className="product-showcase__grid"
          role="img"
          aria-label="A grid of real product photography: the original uploaded photo, plus angle and color variations MerchForge generated from it"
        >
          <div
            ref={heroParallax.ref}
            className="product-showcase__tile product-showcase__tile--hero"
            style={{ transform: `translateY(${heroParallax.offset}px)` }}
          >
            <div className="product-showcase__tile-inner" style={withDelay(0)}>
              <img src={AngleThreeQuarter} alt="Three-quarter angle, generated by MerchForge" />
              <span className="product-showcase__tag">Generated — three-quarter angle</span>
            </div>
          </div>

          <figure className="product-showcase__tile product-showcase__tile--original">
            <div className="product-showcase__tile-inner" style={withDelay(0.08)}>
              <img src={AngleFront} alt="Original product photo, as uploaded" />
              <figcaption>Original photo</figcaption>
            </div>
          </figure>

          <figure className="product-showcase__tile">
            <div className="product-showcase__tile-inner" style={withDelay(0.16)}>
              <img src={AngleBack} alt="Back angle, generated by MerchForge" />
              <figcaption>Generated — back</figcaption>
            </div>
          </figure>

          <div
            ref={tileParallax.ref}
            className="product-showcase__tile"
            style={{ transform: `translateY(${tileParallax.offset}px)` }}
          >
            <div className="product-showcase__tile-inner" style={withDelay(0.24)}>
              <img src={AngleLeft} alt="Left side angle, generated by MerchForge" />
              <span className="product-showcase__tag">Generated — left side</span>
            </div>
          </div>

          <figure className="product-showcase__tile">
            <div className="product-showcase__tile-inner" style={withDelay(0.32)}>
              <img src={ColorA} alt="Alternate color, generated by MerchForge" />
              <figcaption>Generated — new color</figcaption>
            </div>
          </figure>
        </div>
      </div>
    </section>
  );
}
