import { useEffect, useState, type CSSProperties } from 'react';
import useParallax from '../../hooks/useParallax';
import AngleFront from '../../../../assets/Landing/Landing__Showcase__angle-front.jpg';
import AngleBack from '../../../../assets/Landing/Landing__Showcase__angle-back.jpg';
import AngleLeft from '../../../../assets/Landing/Landing__Showcase__angle-left.jpg';
import './Hero.css';

function withDelay(seconds: number): CSSProperties {
  return { '--delay': `${seconds}s` } as CSSProperties;
}

export default function Hero() {
  const [loaded, setLoaded] = useState(false);
  const [primaryRef, primaryOffset] = useParallax<HTMLDivElement>(0.04);
  const [accentARef, accentAOffset] = useParallax<HTMLDivElement>(0.12);
  const [accentBRef, accentBOffset] = useParallax<HTMLDivElement>(0.2);

  useEffect(() => {
    const frame = requestAnimationFrame(() => setLoaded(true));
    return () => cancelAnimationFrame(frame);
  }, []);

  return (
    <section className={`hero${loaded ? ' hero--loaded' : ''}`} aria-label="MerchForge introduction">
      <div className="hero__inner">
        <div className="hero__content">
          <p className="hero__eyebrow" style={withDelay(0)}>
            Product operations, powered by AI
          </p>
          <h1 className="hero__headline" style={withDelay(0.08)}>
            Your products. Your customers.
            <br />
            Your growth — <span className="hero__headline-accent">automated</span>.
          </h1>
          <p className="hero__subtext" style={withDelay(0.16)}>
            MerchForge gives you one place to create, manage, and sell your products —
            powered by AI that turns a photo and a voice note into a finished listing.
          </p>
          <div className="hero__actions" style={withDelay(0.24)}>
            <a href="#get-started" className="hero__btn hero__btn--primary">
              Start Creating
            </a>
            <a href="#capabilities" className="hero__btn hero__btn--secondary">
              See how it works
            </a>
          </div>
        </div>

        <div
          className="hero__visual"
          role="img"
          aria-label="A product photo alongside three angles MerchForge generated from it automatically"
        >
          <div ref={accentARef} className="hero__frame hero__frame--a" style={{ transform: `translateY(${accentAOffset}px)` }}>
            <div className="hero__frame-inner" style={withDelay(0.34)}>
              <img src={AngleBack} alt="Back view, generated by MerchForge AI" />
            </div>
          </div>

          <div ref={primaryRef} className="hero__frame hero__frame--primary" style={{ transform: `translateY(${primaryOffset}px)` }}>
            <div className="hero__frame-inner" style={withDelay(0.24)}>
              <img src={AngleFront} alt="Original product photo, as uploaded by the merchant" fetchPriority="high" />
              <span className="hero__frame-tag">Original photo</span>
            </div>
          </div>

          <div ref={accentBRef} className="hero__frame hero__frame--b" style={{ transform: `translateY(${accentBOffset}px)` }}>
            <div className="hero__frame-inner" style={withDelay(0.44)}>
              <img src={AngleLeft} alt="Left side view, generated by MerchForge AI" />
            </div>
          </div>

          <span className="hero__visual-caption" style={withDelay(0.55)}>
            Generated in every angle — automatically
          </span>
        </div>
      </div>
    </section>
  );
}
