import AngleFront from '../../../../assets/Landing/Landing__Showcase__angle-front.jpg';
import AngleBack from '../../../../assets/Landing/Landing__Showcase__angle-back.jpg';
import AngleLeft from '../../../../assets/Landing/Landing__Showcase__angle-left.jpg';
import CounterBase from '../../../../assets/Landing/Landing__Showcase__counter-base.jpg';
import CounterGreen from '../../../../assets/Landing/Landing__Showcase__counter-green.jpg';
import CounterTerracotta from '../../../../assets/Landing/Landing__Showcase__counter-terracotta.jpg';
import Burger from '../../../../assets/Landing/Landing__Showcase__burger.jpg';

/**
 * The four things MerchForge does to one photograph, one scene each.
 *
 * Every scene shares the same skeleton — a source image on the left, what the
 * product made from it on the right — so moving between them reads as the same
 * idea applied four ways rather than four unrelated slides. Each is remounted
 * when it becomes active, which is what replays its entrance.
 */

/** Staggered reveal: nth child in, at a readable cadence. */
function step(index: number): React.CSSProperties {
    return { '--step': `${0.18 + index * 0.16}s` } as React.CSSProperties;
}

export function AnglesScene() {
    return (
        <div className="scene scene--pair">
            <figure className="scene__source" style={step(0)}>
                <img src={AngleFront} alt="A shirt photographed from the front by the merchant" fetchPriority="high" />
                <figcaption>Your photo</figcaption>
            </figure>

            <div className="scene__output">
                <figure className="scene__card" style={step(1)}>
                    <img src={AngleBack} alt="The same shirt from behind, generated by MerchForge" />
                    <figcaption>Back</figcaption>
                </figure>
                <figure className="scene__card" style={step(2)}>
                    <img src={AngleLeft} alt="The same shirt from the side, generated by MerchForge" />
                    <figcaption>Side</figcaption>
                </figure>
            </div>
        </div>
    );
}

export function ColourwaysScene() {
    return (
        <div className="scene scene--pair">
            <figure className="scene__source" style={step(0)}>
                <img src={CounterBase} alt="An oak counter stool photographed by the merchant" />
                <figcaption>Your photo</figcaption>
            </figure>

            <div className="scene__output">
                <figure className="scene__card" style={step(1)}>
                    <img src={CounterGreen} alt="The same stool finished in forest green, generated by MerchForge" />
                    <figcaption>Forest</figcaption>
                </figure>
                <figure className="scene__card" style={step(2)}>
                    <img src={CounterTerracotta} alt="The same stool finished in terracotta, generated by MerchForge" />
                    <figcaption>Terracotta</figcaption>
                </figure>
            </div>
        </div>
    );
}

/** What the model found, in the order it would surface them. */
const INGREDIENTS = ['Brioche bun, sesame', 'Beef patty', 'Aged cheddar', 'Butter lettuce', 'Tomato', 'Red onion', 'Pickles'];

export function IngredientsScene() {
    return (
        <div className="scene scene--panel">
            <figure className="scene__source" style={step(0)}>
                <img src={Burger} alt="A cheeseburger photographed by the merchant" />
                <figcaption>Your photo</figcaption>
            </figure>

            <div className="scene__readout" style={step(1)}>
                <p className="scene__readout-title">
                    <span className="scene__pulse" aria-hidden="true" />
                    Reading the photo
                </p>

                <ul className="scene__list">
                    {INGREDIENTS.map((item, index) => (
                        <li key={item} style={{ '--step': `${0.5 + index * 0.13}s` } as React.CSSProperties}>
                            {item}
                        </li>
                    ))}
                </ul>
            </div>
        </div>
    );
}

/** Deliberately uneven — round, tidy numbers are the tell that data is invented. */
const REVENUE = [38, 52, 44, 67, 59, 81, 74, 96];
const SPLIT = [
    { label: 'Apparel', share: 0.46 },
    { label: 'Home', share: 0.31 },
    { label: 'Food', share: 0.23 },
];

export function DashboardScene() {
    // Pre-compute the donut arcs. A stroke-dasharray sweep animates cleanly and
    // needs no path maths at runtime.
    const circumference = 2 * Math.PI * 52;

    const arcs = SPLIT.map((slice, index) => ({
        ...slice,
        dash: slice.share * circumference,
        // Where this slice starts: everything before it, as degrees.
        rotation: SPLIT.slice(0, index).reduce((sum, s) => sum + s.share, 0) * 360,
    }));

    return (
        <div className="scene scene--dashboard">
            <div className="scene__panel" style={step(0)}>
                <div className="scene__metric">
                    <p className="scene__metric-label">Revenue, last 30 days</p>
                    <p className="scene__metric-value">$18,420</p>
                    <p className="scene__metric-delta">+12.4%</p>
                </div>

                <div className="scene__bars" role="img" aria-label="Revenue trending upward over the last eight weeks">
                    {REVENUE.map((value, index) => (
                        <span
                            key={index}
                            style={{ '--h': `${value}%`, '--step': `${0.32 + index * 0.07}s` } as React.CSSProperties}
                        />
                    ))}
                </div>
            </div>

            <div className="scene__panel scene__panel--donut" style={step(1)}>
                <svg viewBox="0 0 120 120" aria-label="Sales split by category: apparel 46 percent, home 31 percent, food 23 percent">
                    {arcs.map((arc, index) => (
                        <circle
                            key={arc.label}
                            cx="60"
                            cy="60"
                            r="52"
                            fill="none"
                            strokeWidth="13"
                            strokeDasharray={`${arc.dash} ${circumference}`}
                            transform={`rotate(${arc.rotation - 90} 60 60)`}
                            className={`scene__arc scene__arc--${index}`}
                            style={{ '--step': `${0.6 + index * 0.18}s`, '--dash': `${arc.dash}` } as React.CSSProperties}
                        />
                    ))}
                </svg>

                <ul className="scene__legend">
                    {SPLIT.map((slice, index) => (
                        <li key={slice.label} style={{ '--step': `${0.85 + index * 0.1}s` } as React.CSSProperties}>
                            <span className={`scene__swatch scene__swatch--${index}`} aria-hidden="true" />
                            {slice.label}
                            <b>{Math.round(slice.share * 100)}%</b>
                        </li>
                    ))}
                </ul>
            </div>
        </div>
    );
}

